Given issues with ParseError type, cast to String first
When installing 0.6.0.0 via Homebrew, a compilation error is shown:

    src/Unused/Projection.hs:27:34: error:
        • Expecting two more arguments to ‘ParseError’
          Expected a type, but ‘ParseError’ has kind ‘* -> * -> *’
        • In the first argument of ‘Either’, namely ‘ParseError’
          In the type signature:
            parseTransform :: Text -> Either ParseError ParsedTransform
    cabal: Leaving directory '.'
    cabal: Error: some packages failed to install:
    unused-0.6.0.0 failed during the building phase. The exception was:
    ExitFailure 1

Given we're rendering the output as a string with `show`, this moves
`show` to where we parse and pass the `String` around instead.